### ISSUE TITLE
<> are being escaped automatically to &lt and &gt

### ISSUE THREAD

**Issue by jeevanbmanoj** [dwdyer/reportng#65]
This is what I get in my logs!
<br><font color=red>Duplicate key 9900</font>
I have manually set 	to false and still problem is present. 
Reporter.setEscapeHtml(false);
Thing is in the following line the < and > are taken is &lt and &gt. What am I supposed to do?
Reporter.log("<br><font color=red>Duplicate key " + AfterSplit[0]+"</font>");
if i set escape html to true it becomes
&lt;br&gt;&lt;font color=red&gt;Duplicate key 9900&lt;/font&gt;

**Comment by dwdyer** [comment]
I assume the Reporter.setEscapeHtml method is intended to turn off escaping in the default TestNG HTML reporter, it's not part of ReportNG. To turn off escaping for the ReportNG reporter you need to set the system property "org.uncommons.reportng.escape-output" to false. Full list of supported properties is on the home page: http://reportng.uncommons.org.
